title: Spot Lighting
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: This program demonstrates an implementation for spot lighting in a scene.
language: C++
image:
  icon: https://cloud.githubusercontent.com/assets/10502938/13506660/28be0300-e14d-11e5-90e3-b194f14e52bd.PNG
  banner: https://cloud.githubusercontent.com/assets/10502938/13506660/28be0300-e14d-11e5-90e3-b194f14e52bd.PNG
tags:
  - C++
  - Graphics
extra_resources:
  - "http://www.tomdalling.com/blog/modern-opengl/08-even-more-lighting-directional-lights-spotlights-multiple-lights/"
connections:
  - "directional-lighting-tutorial"
